apiVersion: v1
kind: Service
metadata:
  name: web-a
  namespace: tenant-a
spec:
  selector:
    app: web-a
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP

