apiVersion: v1
kind: Service
metadata:
  name: web-b
  namespace: tenant-b
spec:
  selector:
    app: web-b
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: ClusterIP

